services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        PYTHON_VERSION: 3.12
    container_name: {{ cookiecutter.project_slug }}
    volumes:
      - ..:/workspace:cached 
    working_dir: /workspace/{{ cookiecutter.project_slug }}
    command: sleep infinity
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    tty: true
